### ISSUE TITLE
Fix link to Travis CI in README

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#20]
There is an invalid link to Travis CI in the README file. The correct link is https://travis-ci.org/github/ck3g/homebugh

**Comment by ReyhanSara** [comment]
Hi there, hoping to pull this up for Hacktoberfest :)

**Comment by ck3g** [comment]
Hey @ReyhanSara you're very welcome!

**Comment by ReyhanSara** [comment]
Hi! I'm presently working on this. Could you please assign me to this issue?

**Comment by ReyhanSara** [comment]
Hi. Just submitted my PR but Hacktobest says that the repo is invalid since it does not have the "hactoberfest" label although I see it. Could you please look into this?

**Comment by ck3g** [comment]
Let me check the rules, it looks like something new. I other PRs counts towards Hacktoberfest

**Comment by ck3g** [comment]
I can't find any rules updates. Maybe you need to wait a little bit and then PR will appear in the profile.

**Comment by ck3g** [comment]
Alright. I've added "hacktoberfest" to the topics list. Now it should count.
