### ISSUE TITLE
Fix "Remember me" checkbox position

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#24]
Fix "Remember me" checkbox position on Sign in page

<img width="549" alt="Screenshot 2020-09-21 at 20 12 41" src="https://user-images.githubusercontent.com/123158/93804732-054c8580-fc47-11ea-9b5c-f0c2f3f8a7ec.png">

**Comment by chethanagopinath** [comment]
@ck3g Hi, could I work on this? Or is there another prerequisite here as well?

**Comment by ck3g** [comment]
@chethanagopinath sure you can grab it. There are no prerequisites here.

**Comment by chethanagopinath** [comment]
@ck3g Thanks!

**Comment by chethanagopinath** [comment]
@ck3g Would I need to assign myself?

**Comment by ck3g** [comment]
@chethanagopinath you can yes. So others will know you're going to work or already working on that issue.

**Comment by chethanagopinath** [comment]
@ck3g Hi, I'm not sure how to assign myself :/

**Comment by ck3g** [comment]
You can do it in the top right corner, above the labels.

<img width="346" alt="Screenshot 2020-09-22 at 18 30 32" src="https://user-images.githubusercontent.com/123158/93910726-caf3ee80-fd01-11ea-92b7-2879852acfd8.png">

**Comment by chethanagopinath** [comment]
Weird, I don't have the option to assign myself, not sure if I need access for that or something.

**Comment by ck3g** [comment]
I see, it could be related to some settings. I've assigned it to you

**Comment by ReyhanSara** [comment]
Can I trying working on this too?

**Comment by chethanagopinath** [comment]
@ReyhanSara Hi! I can finish this by myself cause I'll be done in some time.

**Comment by ReyhanSara** [comment]
@chethanagopinath Cool!

**Comment by ck3g** [comment]
Fixed by https://github.com/ck3g/homebugh/pull/93
