### ISSUE TITLE
Make forgot password form wider

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#25]
The forgot password form is too narrow.

Page URL `/users/password/new`

<img width="837" alt="Screenshot 2020-09-21 at 20 15 22" src="https://user-images.githubusercontent.com/123158/93804992-59f00080-fc47-11ea-8396-502680f2675e.png">

**Comment by salonigoyal2309** [comment]
@ck3g I would love to work on this issue for Hacktoberfest 2020 😃

**Comment by ck3g** [comment]
Hey @salonigoyal2309 

Sure! You're welcome

**Comment by salonigoyal2309** [comment]
@ck3g Thanks , can u assign me this issue ? so that I have a hand on issues I have to work on. 😃
