### ISSUE TITLE
Create a User Profile page

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#26]
Create a User Profile page.

* The page should render the current user's email.
* The page should require authorization
* The page should have an `/users/profile` URL.

**Comment by Khush1801** [comment]
Hi! I would like to work on some issues in your project.

**Comment by Khush1801** [comment]
I would like to work on at least 3-4 of your issues. Let me know if I can. Thank you!

**Comment by ck3g** [comment]
You're very welcome. There is a bunch of issues, and I'm going to create more

**Comment by Khush1801** [comment]
Hi
Cool. Can you assign me an issue right now?
I would like to start working on it.
Moreover, I am new to this Hacktoberfest, so would also be participating in
it via your issues only.
I would like you to guide me throughout the process.
Thank you so much!

Thanks and Regards
Khushboo Shah



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/22/20,
10:41:21 PM

**Comment by Khush1801** [comment]
Hi Vitali
Actually I am facing some issues in setting up the project. Can you help me?


Thanks and Regards
Khushboo Shah



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/27/20,
10:11:13 AM

**Comment by ck3g** [comment]
Sure. What is not working for you?

**Comment by Khush1801** [comment]
I am not able to setup mysql correctly i.e. I am getting access denied as
the response whenever I execute any rails command to run the program and I
have  tried all the possible solutions I could find.




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/27/20,
11:20:23 AM

**Comment by ck3g** [comment]
I think you may need to setup MySQL credentials in `config/database.yml`.

If you don't have the file yet, you can copy it from the example file.

```
cp config/database.yml.example config/database.yml
```

try to connect to the MySQL locally and then use the same credentials in the config file. Here is a link that have more information about how to connect https://www.a2hosting.com/kb/developer-corner/mysql/connect-to-mysql-from-the-command-line

**Comment by Khush1801** [comment]
No. It is still not working. I tried all of these. I know in some file I am
supposed to write sudo in front of mysql. I guess that should solve the
problem. But I am not aware of which file it is to be written.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/27/20,
02:52:50 PM

**Comment by ck3g** [comment]
What does `mysql` command returns when you run it from your terminal? Can it connect to MySQL?

**Comment by Khush1801** [comment]
with sudo it connects, without it it does not.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/27/20,
03:52:23 PM

**Comment by ck3g** [comment]
What about?

```shell
mysql -u root
```
or
```shell
mysql -u root -p <YOUR-PASSWORD>
```

If that connects this way, then you need to use your credentials in the `config/database.yml`. 

You can also create a new MySQL user. Here is the page that can help https://linuxize.com/post/how-to-create-mysql-user-accounts-and-grant-privileges/

**Comment by Khush1801** [comment]
No, even these don’t work, tried it all. 
sudo mysql -u root -p works and sudo mysql -u root works.

**Comment by ck3g** [comment]
Then my guess would be to (if possible) MySQL so it could be run without sudo.

**Comment by Khush1801** [comment]
It worked. I reinstalled it. It’s working now.

Thanks a lot for the help.

**Comment by ck3g** [comment]
Awesome!

**Comment by Khush1801** [comment]
Hi Vitali

What are the details that should be reflected on the user profile page?

Thanks and regards
Khushboo Shah



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/02/20,
12:32:23 PM

**Comment by ck3g** [comment]
Hey @Khush1801 

It think for now we can only render the email. That would be enough

**Comment by Khush1801** [comment]
Hi 
Actually, until a while when I was working on the issue everything was working fine but now after sometime when I logged in I am not able to start the rails server. I am not able to understand why. I start rails s and I get an error that the localhost refused to connect.

**Comment by ck3g** [comment]
Does it make any difference if run it via `bundle exec rails s`?

**Comment by Khush1801** [comment]
Nope. Tried that also.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/02/20,
10:30:30 PM

**Comment by ck3g** [comment]
What if you try to run it on a different port? `bundle exec rails s -p 4000` for example

**Comment by ck3g** [comment]
If that won't work, I would suggest to restart a computer =) I have no other ideas

**Comment by Khush1801** [comment]
I tried restarting and then running.. even that didn't work. I will still search for more solutions and let you know.
