### ISSUE TITLE
Fix translation key for Update button on Edit Profile page

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#27]
Page URL: https://homebugh.info/users/edit

<img width="799" alt="Screenshot 2020-09-21 at 20 25 36" src="https://user-images.githubusercontent.com/123158/93805977-c1f31680-fc48-11ea-8587-5425901015b6.png">

**Comment by McAlexVrn** [comment]
@ck3g Hi! This is my PR for you. Happy Hacktoberfest!

**Comment by ck3g** [comment]
Hey @McAlexVrn Thanks!

I've pushed a fix for the greetings =)

**Comment by ck3g** [comment]
@McAlexVrn should I postpone the merge to Oct 1st to make it count for Hacktoberfest? I think it counts only PRs merged in October.

**Comment by McAlexVrn** [comment]
@ck3g I've checked rules and my PR came too early :) Do you mind that I'll recreate this PR on October 1'st?

**Comment by ck3g** [comment]
No problem. =)

But does it needs to be created after October 1st or merged on that date?

**Comment by ck3g** [comment]
From https://hacktoberfest.digitalocean.com/faq

> Yes, all pull requests created between Oct 1 and Oct 31 will count, regardless of when you register for Hacktoberfest. Pull requests created before Oct 1 but merged or marked as ready for review after do not count.

Alright. So feel free to close the PR and create a new one later. I will assign an issue to you, so other will know you're working on it.

Thanks again.

**Comment by McAlexVrn** [comment]
Thanks, pal!
