### ISSUE TITLE
Add development instructions to README

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#29]
Add instructions describing how to configure the project on localhost for development. How to seed the DB etc.

**Comment by Khush1801** [comment]
Hi! Can I work on this issue?

**Comment by ck3g** [comment]
Hey. Absolutely

**Comment by ck3g** [comment]
Hey @Khush1801

I'm sorry, I went ahead and prepare the instructions. I think that should be helpful for others to start.

There is another similar issue you can look at. https://github.com/ck3g/homebugh/issues/38
It's about providing instructions on how to deploy the app on Heroku.

**Comment by Khush1801** [comment]
Hi Vitali
Yes, I saw that.
I think it will be better if I start from the instructions one like even I
will be able to set up things simultaneously.
Let me know if you are okay with it.

Thanks and Regards
Khushboo Shah



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/23/20,
01:16:40 PM
