### ISSUE TITLE
Add option to delete user profile

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#30]
Users (except demo) should be able to remove their accounts with all the data.

Create a "Delete User" page (GET `/user/delete`).
The page should be accessible only for signed-in users.

The page should contain:

* "Delete this user" title
* "Once you delete a user, there is no going back. Please be certain." warning message
* "Current password" field.
* "Delete this user" button

If the form is submitted with a valid password, the current user should be deleted from the database.
If the password is invalid the user should see the validation error message.

**Comment by kyrnich** [comment]
Hey @ck3g 
I'll handle this one.
