### ISSUE TITLE
Add `demo_user` column to `users`

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#34]
Contributes to https://github.com/ck3g/homebugh/issues/33

Add a boolean column `demo_user` to the `users` table with the default value of `false`.

**Comment by phunq-0851** [comment]
@ck3g hey guy, can I take this issue ?

**Comment by ck3g** [comment]
Hey @phunq-0851  sure!

**Comment by phunq-0851** [comment]
> Hey @phunq-0851 sure!

yeah please assign me, hehe
