### ISSUE TITLE
Remove ability to update demo profiles

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#36]
Contributes to https://github.com/ck3g/homebugh/issues/33

Override [`Devise::RegistrationsController#update`](https://github.com/heartcombo/devise/blob/e3a00b27d19ba995891d7dd92394fe2900a789c2/app/controllers/devise/registrations_controller.rb#L50) and skip profile update when the current user is a `demo_user`

### Dependencies

* [x] https://github.com/ck3g/homebugh/issues/34

**Comment by brother-ur** [comment]
Hello @ck3g ! Can I start HactoberFest with it?

**Comment by ck3g** [comment]
Hey @brother-ur sure,

but keep in mind that https://github.com/ck3g/homebugh/issues/34 should be done before.
