### ISSUE TITLE
Migrate from `factory_girl_rails` to `factory_bot_rails`

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#46]
Migrate to the newest possible version of [`factory_bot_rails`](https://github.com/thoughtbot/factory_bot_rails).

Checkout [Upgrade from `factory_girl`](https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md) guide.

**Comment by kyrnich** [comment]
I'll take this one @ck3g

**Comment by ck3g** [comment]
Great. Thanks
