### ISSUE TITLE
Add a Cookie Consent notice

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#53]
Render a Cookie Consent notice to a user at the top of the page.

Check the presence of the `cookie_consent_accepted` cookie on every page load.

If the cookie does not exist, render the "Cookie Consent" popup at the top of the page.
The "Cookie Consent" popup should contain:

*  "Cookie Consent" title
* "We use cookies to give you the best online experience. By using our website, you agree to our use of cookies." message
* "OK" button.

Clicking on the button creates a `cookie_consent_accepted` cookie with the `true` value.

**Comment by vzharkov** [comment]
Hey, I want to help with this issue. Please,  assign it to me.

**Comment by ck3g** [comment]
Thank you
