### ISSUE TITLE
Allow to set show_in_summary value from create account page

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#58]
Allow to set `show_in_summary` value from create account page (`/accounts/new`).

Contributes to https://github.com/ck3g/homebugh/issues/32

Depends on https://github.com/ck3g/homebugh/issues/57

**Comment by m8051** [comment]
@ck3g May I?

**Comment by ck3g** [comment]
@m8051 sure. Keep in mind it depends on https://github.com/ck3g/homebugh/issues/57 But you can prepare PR anyway
