### ISSUE TITLE
Allow to update `show_in_summary` value on edit account page

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#59]
Allow to update `show_in_summary` value on edit account page (`/accounts/:id/edit`).

Contributes to https://github.com/ck3g/homebugh/issues/32

Depends on https://github.com/ck3g/homebugh/issues/57

**Comment by m8051** [comment]
@ck3g following https://github.com/ck3g/homebugh/issues/58 I think it makes sense to tackle this one as well.

**Comment by ck3g** [comment]
Hey @m8051 your last PR implements that feature https://github.com/ck3g/homebugh/pull/82

So I closing it. Thanks
